#!/usr/bin/env Rscript --vanilla
# scripts/build_viber_input.R
# 
# Usage:
#   Rscript --vanilla scripts/build_viber_input.R \
#       <vcf.gz> <seg_tsv> <output.tsv>
#
suppressPackageStartupMessages({
    library(data.table)
    library(VariantAnnotation)
})

args <- commandArgs(trailingOnly = TRUE)

if (length(args) < 3) {
    stop(
        "Usage: build_viber_input.R <vcf.gz> <seg_tsv> <output.tsv>"
    )
}

vcf_file <- args[1]
seg_file <- args[2]
out_file <- args[3]

message("====================================")
message("VIBER Input Preparation (With Copy-Number Neutral Filtering)")
message("VCF:    ", vcf_file)
message("Segs:   ", seg_file)
message("Output: ", out_file)
message("====================================")

# ---------------------------------------------------------
# 1. Read and Process Segmentation File
# ---------------------------------------------------------
if (!file.exists(seg_file)) {
    stop("Segmentation file does not exist: ", seg_file)
}
message("Reading copy-number segments...")
seg <- fread(seg_file)

# Ensure chromosome names align uniformly (e.g., matching "chr1" format)
seg[, chrom_key := paste0("chr", sub("^chr", "", as.character(chrom)))]

# Helper function to find major/minor allele copy numbers
get_cn <- function(chrom, pos) {
    m <- seg[chrom_key == chrom & start <= pos & end >= pos]
    if (nrow(m) == 0L) {
        # Default to neutral diploid if genomic position isn't in segments
        return(c(1L, 1L)) 
    }
    # Using columns generated by your FACETS run script
    major <- max(as.integer(m$mcn[1L]), 0L)
    minor <- max(as.integer(m$lcn[1L]), 0L)
    return(c(major, minor))
}

# ---------------------------------------------------------
# 2. Read and Parse VCF Data
# ---------------------------------------------------------
if (!file.exists(vcf_file)) {
    stop("VCF does not exist: ", vcf_file)
}

message("Reading VCF...")
vcf <- tryCatch(
    readVcf(vcf_file),
    error = function(e) stop("Could not read VCF: ", e$message)
)

n_variants <- length(rowRanges(vcf))
message("Variants in VCF: ", n_variants)

if (n_variants == 0) {
    stop("VCF contains zero variants")
}

ad      <- geno(vcf)$AD
dp      <- geno(vcf)$DP
chrom_v <- as.character(seqnames(rowRanges(vcf)))
pos_v   <- start(rowRanges(vcf))
ref_v   <- as.character(rowRanges(vcf)$REF)
alt_v   <- sapply(rowRanges(vcf)$ALT, function(x) as.character(x[1]))
ref_c_v <- sapply(ad[, 1], `[`, 1)
alt_c_v <- sapply(ad[, 1], `[`, 2)
dp_v    <- dp[, 1]

# ---------------------------------------------------------
# 3. Apply Hard Sequencing Depth Cutoff
# ---------------------------------------------------------
# Bumping cutoff threshold to 30x to suppress downstream subclonal noise
depth_keep <- !is.na(ref_c_v) & !is.na(alt_c_v) & dp_v >= 25
message(sprintf("Mutations passing depth filter (>=30x): %d / %d", sum(depth_keep), length(depth_keep)))

# Slice vectors to keep passing positions
chrom_v <- chrom_v[depth_keep]; pos_v   <- pos_v[depth_keep]
ref_v   <- ref_v[depth_keep];   alt_v   <- alt_v[depth_keep]
ref_c_v <- ref_c_v[depth_keep]; alt_c_v <- alt_c_v[depth_keep]
dp_v    <- dp_v[depth_keep]

if (length(chrom_v) < 10) {
    stop("Fewer than 10 mutations remaining after depth filtering.")
}

# ---------------------------------------------------------
# 4. Annotate Copy Number States & Filter for Neutrality
# ---------------------------------------------------------
message("Annotating positions with major/minor copy number states...")
cn_mat <- mapply(get_cn, chrom_v, pos_v)
major_cn_v <- cn_mat[1, ]
minor_cn_v <- cn_mat[2, ]

# Build initial table
dat <- data.table(
    mutation_id = paste0(chrom_v, ":", pos_v, ":", ref_v, ">", alt_v),
    successes   = as.integer(alt_c_v),
    trials      = as.integer(dp_v),
    major_cn    = major_cn_v,
    minor_cn    = minor_cn_v
)

# Apply copy number neutrality selection filter
# True diploid space means major == 1 and minor == 1
cn_keep_idx <- dat$major_cn == 1 & dat$minor_cn == 1
message(sprintf("Mutations in copy-number neutral diploid regions (1+1): %d / %d", sum(cn_keep_idx), nrow(dat)))

dat <- dat[cn_keep_idx]

# Remove temporary columns so VIBER receives only what it explicitly requires
dat[, c("major_cn", "minor_cn") := NULL]

# ---------------------------------------------------------
# 5. Sanity Checks & Warnings
# ---------------------------------------------------------
message("Running validation checks on finalized subset...")

if (any(dat$successes < 0)) {
    stop("Negative alternate allele counts found!")
}
if (any(dat$trials <= 0)) {
    stop("Zero or negative sequencing coverage found!")
}
if (any(dat$successes > dat$trials)) {
    bad <- dat[successes > trials]
    print(head(bad))
    stop("Found variants with alternate read counts greater than total depth!")
}

# Deduplicate if duplicate variant strings slip through
if (anyDuplicated(dat$mutation_id)) {
    warning("Duplicate mutation IDs identified: ", sum(duplicated(dat$mutation_id)), " - removing duplicates.")
    dat <- unique(dat)
}

if (nrow(dat) < 10) {
    stop("Too few mutations remaining (fewer than 10) to reliably run VIBER.")
}

# ---------------------------------------------------------
# 6. Profile Metrics & Output Save
# ---------------------------------------------------------
dat[, VAF := successes / trials]

message("")
message("Summary stats of filtered inputs:")
print(summary(dat))

message("\nMean VAF: ", round(mean(dat$VAF), 4))
message("Median VAF: ", round(median(dat$VAF), 4))

if (mean(dat$VAF) > 0.85) {
    warning("Extremely high mean VAF (>0.85). Verify germline variants were fully filtered.")
}
if (median(dat$VAF) < 0.01) {
    warning("Very low median VAF. Double-check variant selection filters.")
}

# Strip temporary tracking column
dat[, VAF := NULL]

# Write to disk
dir.create(dirname(out_file), showWarnings = FALSE, recursive = TRUE)
fwrite(dat, out_file, sep = "\t")
message("\nSuccess! Parsed input saved to: ", out_file)


# old version: 
##!/usr/bin/env Rscript --vanilla
#
#suppressPackageStartupMessages({
#    library(data.table)
#    library(VariantAnnotation)
#})
#
#
#args <- commandArgs(trailingOnly=TRUE)
#
#if (length(args) < 2) {
#    stop(
#        "Usage: build_viber_input.R <vcf.gz> <output.tsv>"
#    )
#}
#
#vcf_file <- args[1]
#out_file <- args[2]
#
#
#message("====================================")
#message("VIBER input preparation")
#message("VCF: ", vcf_file)
#message("Output: ", out_file)
#message("====================================")
#
#
## ---------------------------------------------------------
## Read VCF
## ---------------------------------------------------------
#
#if (!file.exists(vcf_file)) {
#    stop("VCF does not exist: ", vcf_file)
#}
#
#
#message("Reading VCF...")
#
#vcf <- tryCatch(
#    readVcf(vcf_file),
#    error=function(e)
#        stop("Could not read VCF: ", e$message)
#)
#
#
#n_variants <- length(rowRanges(vcf))
#
#message(
#    "Variants in VCF: ",
#    n_variants
#)
#
#
#if (n_variants == 0) {
#    stop("VCF contains zero variants")
#}
#
#
## ---------------------------------------------------------
## Extract allele counts
## ---------------------------------------------------------
#
#ad <- geno(vcf)$AD
#dp <- geno(vcf)$DP
#
#
#if (is.null(ad)) {
#    stop(
#        "VCF has no AD field. VIBER requires allele counts."
#    )
#}
#
#
#if (is.null(dp)) {
#    warning(
#        "VCF has no DP field. Using AD-derived depth."
#    )
#}
#
#
#chrom <- as.character(seqnames(rowRanges(vcf)))
#pos   <- start(rowRanges(vcf))
#
#
#ref <- sapply(
#    ad[,1],
#    `[`,
#    1
#)
#
#alt <- sapply(
#    ad[,1],
#    `[`,
#    2
#)
#
#
#if (is.null(dp)) {
#    depth <- ref + alt
#} else {
#    depth <- dp[,1]
#}
#
#
#
## ---------------------------------------------------------
## Filtering
## ---------------------------------------------------------
#
#message("Applying filters")
#
#keep <- 
#    !is.na(ref) &
#    !is.na(alt) &
#    !is.na(depth) &
#    depth >= 10 &
#    alt >= 1
#
#
#message(
#    "Variants retained: ",
#    sum(keep),
#    " / ",
#    length(keep)
#)
#
#
#if (sum(keep) < 10) {
#    stop(
#        "Too few mutations after filtering: ",
#        sum(keep),
#        ". VIBER needs more variants."
#    )
#}
#
#
## ---------------------------------------------------------
## Build table
## ---------------------------------------------------------
#
#dat <- data.table(
#
#    mutation_id =
#        paste0(
#            chrom[keep],
#            ":",
#            pos[keep]
#        ),
#
#    successes =
#        as.integer(alt[keep]),
#
#    trials =
#        as.integer(depth[keep])
#)
#
#
## ---------------------------------------------------------
## Sanity checks
## ---------------------------------------------------------
#
#message("Running sanity checks")
#
#
#if (any(dat$successes < 0)) {
#    stop("Negative alternate counts found")
#}
#
#
#if (any(dat$trials <= 0)) {
#    stop("Zero/negative coverage found")
#}
#
#
#if (any(dat$successes > dat$trials)) {
#
#    bad <- dat[
#        successes > trials
#    ]
#
#    print(head(bad))
#
#    stop(
#        "Found variants with ALT count > total depth"
#    )
#}
#
#
#if (anyDuplicated(dat$mutation_id)) {
#
#    warning(
#        "Duplicate mutation IDs found: ",
#        sum(duplicated(dat$mutation_id))
#    )
#
#    dat <- unique(dat)
#}
#
#
#
#dat[, VAF := successes / trials]
#
#
#message("")
#message("Input summary:")
#print(summary(dat))
#
#
#message("")
#message("Input head:")
#print(head(dat, 10))
#
#
#message("")
#message(
#    "Mean VAF: ",
#    round(mean(dat$VAF), 4)
#)
#
#message(
#    "Median VAF: ",
#    round(median(dat$VAF), 4)
#)
#
#
#if (mean(dat$VAF) > 0.9) {
#    warning(
#        "Mean VAF > 0.9. Check whether germline variants were filtered."
#    )
#}
#
#
#if (median(dat$VAF) < 0.005) {
#    warning(
#        "Very low median VAF. Check filtering and sequencing depth."
#    )
#}
#
#
#
## Remove helper column
#
#dat[, VAF := NULL]
#
#
## ---------------------------------------------------------
## Write
## ---------------------------------------------------------
#
#dir.create(
#    dirname(out_file),
#    recursive=TRUE,
#    showWarnings=FALSE
#)
#
#
#fwrite(
#    dat,
#    out_file,
#    sep="\t"
#)
#
#
#message("")
#message(
#    "Finished. Written ",
#    nrow(dat),
#    " mutations to ",
#    out_file
#)
#